# Pledge 관련 feature engineering¶

In [4]:
from tqdm import tqdm
from tqdm import trange
from itertools import chain
from scipy import stats
from datetime import timedelta 
import warnings
warnings.filterwarnings('ignore')
import pickle
import datetime as dt
import networkx as nx
import pickle
import pandas as pd

In [9]:
# train data 

label = pd.read_csv('C:/Users/CPB06GameN/Desktop/빅콘/2019_빅콘테스트_챔피언스리그_데이터/train_label.csv')
pledge = pd.read_csv('C:/Users/CPB06GameN/Desktop/빅콘/2019_빅콘테스트_챔피언스리그_데이터/train_pledge.csv')
pledge.tail()

,day,acc_id,char_id,server,pledge_id,play_char_cnt,combat_char_cnt,pledge_combat_cnt,random_attacker_cnt,random_defender_cnt,same_pledge_cnt,temp_cnt,etc_cnt,combat_play_time,non_combat_play_time
1083379,28,20832,289875,br,21017,0.108268,0.072179,0.0,0.0,0.0,0.0,0.098883,0.007078,0.024209,0.000000
1083380,28,95161,391606,br,21017,0.108268,0.072179,0.0,0.0,0.0,0.0,0.098883,0.007078,0.024209,0.000000
1083381,28,79704,363505,br,21017,0.108268,0.072179,0.0,0.0,0.0,0.0,0.098883,0.007078,0.024209,0.000000
1083382,28,25252,167709,br,3587,0.072179,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.028031
1083383,28,99121,13325,br,31353,0.036089,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.004170

### 1. 혈맹당 참여 인원수 (혈맹의 크기를 보기 위함) _ 이미 구해진 데이터를 활용

### 혈맹 관련 전처리는 데이터 자체가 다른 성격이라 참고하기 힘들 것 같다